package com.cn.cloudpictureplatform.infrastructure.persistence;

import com.cn.cloudpictureplatform.domain.picture.PictureTag;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.UUID;

@Repository
public interface PictureTagRepository extends JpaRepository<PictureTag, UUID> {
    List<PictureTag> findByPictureAssetId(UUID pictureAssetId);

    List<PictureTag> findByPictureAssetIdOrderByCreatedAtDesc(UUID pictureAssetId);

    List<PictureTag> findByTagId(UUID tagId);

    @Query("SELECT t FROM PictureTag t WHERE t.pictureAssetId = :pictureAssetId AND t.isAutoGenerated = true")
    List<PictureTag> findAutoGeneratedTagsByPictureAssetId(@Param("pictureAssetId") UUID pictureAssetId);

    long countByTagId(UUID tagId);

    void deleteByPictureAssetId(UUID pictureAssetId);
}
