package com.cn.cloudpictureplatform.domain.picture;

import com.cn.cloudpictureplatform.common.model.BaseEntity;
import jakarta.persistence.*;
import lombok.*;

import java.util.UUID;

@Getter
@Setter
@Builder
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name = "picture_tag")
public class PictureTag extends BaseEntity {

    @Column(name = "picture_asset_id", nullable = false, columnDefinition = "uuid")
    private UUID pictureAssetId;

    @Column(name = "tag_text", nullable = false, length = 100)
    private String tagText;

    @Column(name = "tag_id", columnDefinition = "uuid")
    private UUID tagId;

    @Column(name = "confidence_score")
    private Double confidenceScore;

    @Column(name = "provider", length = 50)
    private String provider;

    @Column(name = "is_auto_generated")
    private Boolean isAutoGenerated = true;
}
