app:
  security:
    jwt:
      secret: ${JWT_SECRET}
  storage:
    provider: ${STORAGE_PROVIDER:cos}

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  datasource:
    password: ${DB_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
