package com.cn.cloudpictureplatform.interfaces.picture.dto;

import java.time.Instant;
import java.util.UUID;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;

@Getter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PictureTagResponse {

    private UUID id;
    private UUID pictureAssetId;
    private UUID tagId;
    private String tagText;
    private Double confidenceScore;
    private String provider;
    private Boolean autoGenerated;
    private Instant createdAt;
}
