package com.cn.cloudpictureplatform.interfaces.picture.dto;

import java.util.List;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.Size;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@NoArgsConstructor
public class PictureTagCreateRequest {

    @NotEmpty
    @Valid
    private List<PictureTagItemRequest> tags;

    @Size(max = 50)
    private String provider;

    private Boolean autoGenerated;
}
