package com.cn.cloudpictureplatform.infrastructure.ai.consumer;

import java.util.List;
import java.util.Map;
import java.util.UUID;
import org.springframework.amqp.rabbit.annotation.RabbitListener;
import org.springframework.boot.autoconfigure.condition.ConditionalOnClass;
import org.springframework.stereotype.Component;
import com.cn.cloudpictureplatform.application.picture.PictureTagService;
import com.cn.cloudpictureplatform.infrastructure.persistence.AiTaskRepository;
import com.cn.cloudpictureplatform.domain.ai.AiTask;
import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.extern.slf4j.Slf4j;

@Slf4j
@Component
@ConditionalOnClass(name = "org.springframework.amqp.rabbit.annotation.RabbitListener")
public class AiTaggingResultConsumer {
    private final PictureTagService pictureTagService;
    private final AiTaskRepository aiTaskRepository;
    private final ObjectMapper objectMapper;

    public AiTaggingResultConsumer(
            PictureTagService pictureTagService,
            AiTaskRepository aiTaskRepository,
            ObjectMapper objectMapper
    ) {
        this.pictureTagService = pictureTagService;
        this.aiTaskRepository = aiTaskRepository;
        this.objectMapper = objectMapper;
    }

    @RabbitListener(queues = "ai.tagging.result")
    public void onTaggingResult(String message) {
        try {
            @SuppressWarnings("unchecked")
            Map<String, Object> msg = objectMapper.readValue(message, Map.class);
            UUID pictureId = UUID.fromString((String) msg.get("pictureId"));
            boolean success = Boolean.TRUE.equals(msg.get("success"));
            if (success) {
                @SuppressWarnings("unchecked")
                List<Map<String, Object>> tags = (List<Map<String, Object>>) msg.get("tags");
                for (Map<String, Object> tag : tags) {
                    String tagText = (String) tag.get("label");
                    if (tagText == null) tagText = (String) tag.get("text");
                    pictureTagService.addAutoGeneratedTag(
                            pictureId,
                            tagText,
                            ((Number) tag.get("confidence")).doubleValue(),
                            (String) msg.get("provider")
                    );
                }
                log.info("AI tagging applied: pictureId={}, tags={}", pictureId, tags.size());
            } else {
                log.warn("AI tagging failed: pictureId={}, error={}", pictureId, msg.get("errorMessage"));
            }
            markTaskCompleted(pictureId, success);
        } catch (Exception ex) {
            log.error("Failed to process tagging result", ex);
        }
    }

    private void markTaskCompleted(UUID pictureId, boolean success) {
        try {
            var tasks = aiTaskRepository.findAll();
            for (AiTask task : tasks) {
                if (task.getPictureId() != null && task.getPictureId().equals(pictureId)
                        && "PENDING".equals(task.getStatus())) {
                    task.setStatus(success ? "COMPLETED" : "FAILED");
                    task.setCompletedAt(java.time.Instant.now());
                    aiTaskRepository.save(task);
                    return;
                }
            }
        } catch (Exception ex) {
            log.warn("Failed to mark AI task completed", ex);
        }
    }
}
