package com.cn.cloudpictureplatform.application.picture;

import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import java.util.UUID;
import java.util.stream.Collectors;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.util.StringUtils;
import com.cn.cloudpictureplatform.application.search.SearchIndexService;
import com.cn.cloudpictureplatform.common.exception.ApiException;
import com.cn.cloudpictureplatform.common.web.ApiErrorCode;
import com.cn.cloudpictureplatform.domain.picture.PictureTag;
import com.cn.cloudpictureplatform.domain.picture.Tag;
import com.cn.cloudpictureplatform.infrastructure.persistence.PictureTagRepository;
import com.cn.cloudpictureplatform.infrastructure.persistence.TagRepository;
import com.cn.cloudpictureplatform.infrastructure.persistence.PictureAssetRepository;
import com.cn.cloudpictureplatform.application.picture.dto.PictureTagCreateRequest;
import com.cn.cloudpictureplatform.application.picture.dto.PictureTagItemRequest;
import com.cn.cloudpictureplatform.application.shared.dto.PictureTagResponse;

@Service
@Transactional(readOnly = true)
public class PictureTagService {
    private final PictureTagRepository pictureTagRepository;
    private final TagRepository tagRepository;
    private final PictureAssetRepository pictureAssetRepository;
    private final SearchIndexService searchIndexService;

    public PictureTagService(
            PictureTagRepository pictureTagRepository,
            TagRepository tagRepository,
            PictureAssetRepository pictureAssetRepository,
            SearchIndexService searchIndexService
    ) {
        this.pictureTagRepository = pictureTagRepository;
        this.tagRepository = tagRepository;
        this.pictureAssetRepository = pictureAssetRepository;
        this.searchIndexService = searchIndexService;
    }

    public List<PictureTagResponse> listTags(UUID pictureId) {
        verifyPictureExists(pictureId);
        return pictureTagRepository.findByPictureAssetIdOrderByCreatedAtDesc(pictureId).stream()
                .map(this::toTagResponse)
                .toList();
    }

    @Transactional
    public List<PictureTagResponse> addTags(UUID pictureId, PictureTagCreateRequest request) {
        if (request == null || request.getTags() == null || request.getTags().isEmpty()) {
            throw new ApiException(ApiErrorCode.BAD_REQUEST, "tags are required");
        }
        verifyPictureExists(pictureId);
        String provider = StringUtils.hasText(request.getProvider()) ? request.getProvider().trim() : null;
        boolean autoGenerated = Boolean.TRUE.equals(request.getAutoGenerated());
        List<PictureTag> existingTags = pictureTagRepository.findByPictureAssetId(pictureId);
        Set<String> existingKeys = existingTags.stream()
                .map(tag -> buildTagKey(tag.getTagText(), tag.getProvider(), tag.getIsAutoGenerated()))
                .collect(Collectors.toSet());

        List<PictureTag> toSave = new ArrayList<>();
        for (PictureTagItemRequest item : request.getTags()) {
            String tagText = item == null ? null : item.getText();
            if (!StringUtils.hasText(tagText)) {
                throw new ApiException(ApiErrorCode.BAD_REQUEST, "tag text is required");
            }
            String trimmed = tagText.trim();
            Tag catalog = findOrCreateTag(trimmed);
            String key = buildTagKey(trimmed, provider, autoGenerated);
            if (existingKeys.contains(key)) {
                continue;
            }
            PictureTag tag = PictureTag.builder()
                    .pictureAssetId(pictureId)
                    .tagId(catalog == null ? null : catalog.getId())
                    .tagText(trimmed)
                    .confidenceScore(item.getConfidenceScore())
                    .provider(provider)
                    .isAutoGenerated(autoGenerated)
                    .build();
            toSave.add(tag);
            existingKeys.add(key);
        }

        if (!toSave.isEmpty()) {
            pictureTagRepository.saveAll(toSave);
            searchIndexService.enqueuePicture(pictureId);
        }
        return listTags(pictureId);
    }

    @Transactional
    public void removeTag(UUID pictureId, UUID tagId) {
        verifyPictureExists(pictureId);
        PictureTag tag = pictureTagRepository.findById(tagId)
                .orElseThrow(() -> new ApiException(ApiErrorCode.NOT_FOUND, "tag not found"));
        if (!pictureId.equals(tag.getPictureAssetId())) {
            throw new ApiException(ApiErrorCode.NOT_FOUND, "tag not found");
        }
        pictureTagRepository.delete(tag);
        searchIndexService.enqueuePicture(pictureId);
    }

    private PictureTagResponse toTagResponse(PictureTag tag) {
        return PictureTagResponse.builder()
                .id(tag.getId())
                .pictureAssetId(tag.getPictureAssetId())
                .tagId(tag.getTagId())
                .tagText(tag.getTagText())
                .confidenceScore(tag.getConfidenceScore())
                .provider(tag.getProvider())
                .autoGenerated(tag.getIsAutoGenerated())
                .createdAt(tag.getCreatedAt())
                .build();
    }

    private String buildTagKey(String tagText, String provider, boolean autoGenerated) {
        String normalizedText = tagText == null ? "" : tagText.trim().toLowerCase();
        String normalizedProvider = provider == null ? "" : provider.trim().toLowerCase();
        return normalizedText + "|" + normalizedProvider + "|" + autoGenerated;
    }

    private void verifyPictureExists(UUID pictureId) {
        if (pictureId == null || !pictureAssetRepository.existsById(pictureId)) {
            throw new ApiException(ApiErrorCode.NOT_FOUND, "picture not found");
        }
    }

    private Tag findOrCreateTag(String tagName) {
        if (!StringUtils.hasText(tagName)) {
            return null;
        }
        String name = tagName.trim().toLowerCase();
        return tagRepository.findByNameIgnoreCase(name)
                .orElseGet(() -> {
                    Tag tag = new Tag();
                    tag.setName(name);
                    return tagRepository.save(tag);
                });
    }
}
